name: Docker Test

on: [pull_request, workflow_dispatch]
jobs:
  test:
    name: Run test suite
    runs-on: ubuntu-latest
    timeout-minutes: 2.5
    env:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "notes_data"
      COMPOSE_FILE: ./server/docker-compose.yml
      DOCKER_USER: ${{ secrets.DOCKER_USER }}
      DOCKER_PASS: ${{ secrets.DOCKER_PASS }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to DockerHub
        run: docker login -u $DOCKER_USER -p $DOCKER_PASS

      - name: Build docker images
        run: docker-compose build

      - name: Run tests
        run: docker-compose up
