name: Test

on: [pull_request, workflow_dispatch]

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./client
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node_version: '14'
      - name: Install npm packages
        run: npm install
      - name: Check Linting with Eslint
        run: npm run lint
